name       : fs-uae-arcade-dev
version    : 2.9.7
release    : 6
source     :
    - https://fs-uae.net/devel/2.9.7dev2/fs-uae-arcade-2.9.7dev2.tar.gz : f1d0610a8e87ead4d4d0321a972854c78707a46f452ee2a23603623f44f8f681
license    : GPL-2.0
component  : games.emulator
summary    : Arcade Frontend for FS-UAE Amiga Emulator (Development Version).
description: |
    An easy-to-use graphical configuration program which allows you to enjoy FS-UAE and Amiga emulation without writing configuration files.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - fs-uae-dev
    - python-lhafile
    - python3-qt5
build      : |
    %python3_setup
install    : |
    python3 setup.py install --install-lib=%installroot%/usr/share/fs-uae-arcade install --install-scripts=%installroot%/usr/bin
