name       : fs-uae-arcade-dev
version    : 3.0.5
release    : 7
source     :
    - https://fs-uae.net/stable/3.0.5/fs-uae-arcade-3.0.5.tar.gz : f0c8b5089b604090b5a629297b726a15d4cf77572185766de44d712e96617fae
license    : GPL-2.0-or-later
component  : games.emulator
homepage   : https://fs-uae.net/
summary    : Arcade Frontend for FS-UAE Amiga Emulator (Development Version)
description: |
    An easy-to-use graphical configuration program which allows you to enjoy FS-UAE and Amiga emulation without writing configuration files.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - fs-uae-dev
    - python-lhafile
    - python3-qt5
build      : |
    %make
install    : |
    %make_install DESTDIR="$installdir" prefix=/usr
    rm -rf $installdir/usr/share/doc/
