name       : fs-uae-arcade-dev
version    : 2.7.6
release    : 1
source     :
    - http://fs-uae.net/fs-uae/devel/2.7.6dev/fs-uae-arcade-2.7.6dev.tar.gz : f31c57cc72ca4378297b4be0206862e508709ed596e84d16d062f986dbb2005e
license    : GPL-2.0
summary    : Arcade Frontend for FS-UAE Amiga Emulator (Development Version).
description: An easy-to-use graphical configuration program which allows you to enjoy FS-UAE and Amiga emulation without writing configuration files.
builddeps  :  
    - pkgconfig(python-3.4)
    - python3-qt5
    - python3-setuptools
build      : |
    python3 setup.py build
install    : |
    python3 setup.py install --install-lib=%installroot%/usr/share/fs-uae-arcade install --install-scripts=%installroot%/usr/bin
    %make_install
